version: "3.1"

services:
  web:
    build:
      context: .
    environment:
      DB_NAME: 'words_data'
      DB_PASSWORD: 'abacabadabacaba'
      DB_USER: 'doubletapp_api'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      SECRET_KEY: '2283221337'
      API_SECRET: 'i love doubletapp'
      DJANGO_DEBUG: 'False'
    expose:
      - 13337
    depends_on:
      - postgres
    restart: on-failure

    volumes:
      - static-files:/app/static/
      - migration-volume:/app/api/migrations

    command: >
      sh -c "/app/wait-for postgres:5432 --timeout 5 -- 
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py createsuperuser_if_nonexist --username admin --password admin &&
             python3 manage.py collectstatic --no-input &&
             gunicorn --bind 0.0.0.0:13337 --access-logfile - double_trouble.wsgi:application"

  postgres:
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_PASSWORD: 'abacabadabacaba'
      POSTGRES_USER: 'doubletapp_api'
      POSTGRES_DB: 'words_data'
    volumes:
      - words-db:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    build:
      context: ./nginx
    ports:
      - '8080:8228'
    volumes:
      - static-files:/data/www/static
    depends_on:
      - web

volumes:
  words-db:
  static-files:
  migration-volume: